name: Build OpenFFBoard firmware

inputs:
  target: 
    description: 'make target'
    required: true
  path: 
    description: 'output path in firmwarepath ./Firmware/<path>'
    required: true
    default: 'Output'
  firmwarepath: 
    description: 'Input path. Normally ./Firmware'
    required: true
    default: './Firmware'


runs:
  using: "composite"
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2
    - name: "Check toolchain exists"
      id: check_tc
      uses: andstor/file-existence-action@v3
      with:
        files: "/tmp/armtc,/usr/share/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi"

    - name: Make temp dir
      if: steps.check_tc.outputs.files_exists != 'true'
      shell: bash
      run: mkdir -p /tmp/armtc # make temp directory

    # Setup toolchain
    - uses: actions/cache@v4
      id: cache
      if: steps.check_tc.outputs.files_exists != 'true'
      with:
        path: /tmp/armtc
        key: 'arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi'

    - name: Download toolchain
      shell: bash
      if: steps.check_tc.outputs.files_exists != 'true' && steps.cache.outputs.cache-hit != 'true'
      run: wget -q --no-check-certificate -O /tmp/armtc/gcc-arm-none-eabi.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
      
    - name: Setup environment
      if: steps.check_tc.outputs.files_exists != 'true'
      shell: bash
      run: | 
        sudo tar xf /tmp/armtc/gcc-arm-none-eabi.tar.xz -C /usr/share/
        sudo ln -s /usr/share/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/* /usr/bin/

    - name: Build ${{ inputs.target }}
      shell: bash
      run: |
        make -C ${{ inputs.firmwarepath }} clean
        make hexmetadata -j -C ${{ inputs.firmwarepath }} MCU_TARGET=${{ inputs.target }} OUTPUT_DIR=${{ inputs.path }}

