/*
 * HID PID packet handling (HidFFB.cpp)
 *
 * Tests how the PID reports sent by a host are translated into the internal effect storage.
 * Reports are generated by PidHost which mimics the operating systems PID driver.
 *
 * Reference: Device Class Definition for PID 1.01
 * https://usb.org/sites/default/files/documents/pid1_01.pdf
 *
 * Test cases named "characterization" document the current behaviour of the firmware
 * for later verification against the PID specification. They do not claim it is correct.
 */
#include "doctest.h"
#include "TestHelpers.h"
#include "FfbFixture.h"

#include <cmath>

using doctest::Approx;

TEST_SUITE("HidFFB") {

// ---------------------------------------------------------------------------
// Report layouts. Must match the HID report descriptor (usb_hid_ffb_desc.h)
// ---------------------------------------------------------------------------

TEST_CASE("report structs have the size defined by the report descriptor") {
	CHECK(sizeof(FFB_SetEffect_t) == 18);
	CHECK(sizeof(FFB_SetEnvelope_Data_t) == 14);
	CHECK(sizeof(FFB_SetCondition_Data_t) == 15);
	CHECK(sizeof(FFB_SetPeriodic_Data_t) == 12);
	CHECK(sizeof(FFB_SetConstantForce_Data_t) == 4);
	CHECK(sizeof(FFB_SetRamp_Data_t) == 6);
	CHECK(sizeof(FFB_EffOp_Data_t) == 4);
	CHECK(sizeof(FFB_CreateNewEffect_Feature_Data_t) == 3);
	CHECK(sizeof(FFB_BlockLoad_Feature_Data_t) == 4);
	CHECK(sizeof(FFB_PIDPool_Feature_Data_t) == 4);
	CHECK(sizeof(reportFFB_status_t) == 2);
}

// ---------------------------------------------------------------------------
// Setup and pool
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "handler registers for hid reports") {
	CHECK(UsbHidHandler::globalHidHandler == &ffb);
	CHECK_FALSE(ffb.getFfbActive());
	CHECK_FALSE(ec->isActive());
}

TEST_CASE("handler unregisters when destroyed" * KNOWN_ISSUE("HidFFB does not clear UsbHidHandler::globalHidHandler in its destructor. Reports received afterwards use a dangling pointer")) {
	FirmwareFixture fixture;
	{
		auto ec = std::make_shared<EffectsCalculator>();
		HidFFB ffb(ec, 2);
	}
	bool unregistered = UsbHidHandler::globalHidHandler == nullptr;
	UsbHidHandler::globalHidHandler = nullptr;
	CHECK(unregistered);
}

TEST_CASE_FIXTURE(FfbFixture, "pool report describes the effect storage") {
	PidHost::Pool pool = host.pool();
	CHECK(pool.maxSimultaneousEffects == MAX_EFFECTS);
	CHECK(pool.ramPoolSize == (uint16_t)(MAX_EFFECTS * sizeof(FFB_Effect)));
	CHECK(pool.memoryManagement == 1);
}

TEST_CASE_FIXTURE(FfbFixture, "unknown feature reports are not answered") {
	CHECK(host.getFeature(0x55).empty());
}

// ---------------------------------------------------------------------------
// Effect allocation (Create New Effect, Block Load, Block Free)
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "create new effect allocates the first free block") {
	host.createNewEffect(FFB_EFFECT_CONSTANT);
	PidHost::BlockLoad load = host.blockLoad();

	CHECK(load.loadStatus == PidHost::LOAD_SUCCESS);
	CHECK(load.effectBlockIndex == 1);
	CHECK(effect(1).type == FFB_EFFECT_CONSTANT);
	CHECK(effect(1).state == 0); // Not started yet

	CHECK(host.allocateEffect(FFB_EFFECT_SINE) == 2);
	CHECK(effect(2).type == FFB_EFFECT_SINE);
}

TEST_CASE_FIXTURE(FfbFixture, "every effect type can be allocated") {
	for (uint8_t type = FFB_EFFECT_CONSTANT; type <= FFB_EFFECT_CUSTOM; type++) {
		CAPTURE(type);
		uint8_t index = host.allocateEffect(type);
		CHECK(index == type);
		CHECK(effect(index).type == type);
	}
}

TEST_CASE_FIXTURE(FfbFixture, "new effects have default parameters") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_SPRING);
	FFB_Effect &fx = effect(index);
	CHECK(fx.gain == 255);
	CHECK(fx.magnitude == 0);
	CHECK(fx.offset == 0);
	CHECK(fx.duration == FFB_EFFECT_DURATION_INFINITE);
	CHECK(fx.useEnvelope == false);
	CHECK(fx.useSingleCondition == true);
	CHECK(fx.axisMagnitudes[0] == 0);
	CHECK(fx.axisMagnitudes[1] == 0);
	CHECK_FALSE(fx.conditions[0].isActive());
}

TEST_CASE_FIXTURE(FfbFixture, "filters are created depending on the effect type") {
	CHECK(effect(host.allocateEffect(FFB_EFFECT_CONSTANT)).filter[0] != nullptr);
	CHECK(effect(host.allocateEffect(FFB_EFFECT_DAMPER)).filter[1] != nullptr);
	CHECK(effect(host.allocateEffect(FFB_EFFECT_FRICTION)).filter[0] != nullptr);
	CHECK(effect(host.allocateEffect(FFB_EFFECT_INERTIA)).filter[0] != nullptr);
	CHECK(effect(host.allocateEffect(FFB_EFFECT_SPRING)).filter[0] == nullptr);
	CHECK(effect(host.allocateEffect(FFB_EFFECT_SINE)).filter[0] == nullptr);
}

TEST_CASE_FIXTURE(FfbFixture, "allocation fails with status full when all blocks are used") {
	for (int i = 1; i <= MAX_EFFECTS; i++) {
		CHECK(host.allocateEffect(FFB_EFFECT_CONSTANT) == i);
	}
	host.createNewEffect(FFB_EFFECT_CONSTANT);
	CHECK(host.blockLoad().loadStatus == PidHost::LOAD_FULL);

	// Works again after freeing a block
	host.blockFree(7);
	CHECK(host.allocateEffect(FFB_EFFECT_SINE) == 7);
}

TEST_CASE_FIXTURE(FfbFixture, "characterization: invalid effect types are rejected with status full") {
	// PID 1.01 defines Block Load Error (3) for this case
	for (uint8_t type : {(uint8_t)FFB_EFFECT_NONE, (uint8_t)(FFB_EFFECT_CUSTOM + 1), (uint8_t)0xFF}) {
		CAPTURE(type);
		host.createNewEffect(type);
		CHECK(host.blockLoad().loadStatus == PidHost::LOAD_FULL);
	}
	CHECK(effect(1).type == FFB_EFFECT_NONE);
}

TEST_CASE_FIXTURE(FfbFixture, "block free releases and resets an effect") {
	uint8_t index = startEffect(FFB_EFFECT_CONSTANT);
	host.setConstantForce(index, 1000);
	REQUIRE(effect(index).state == 1);

	host.blockFree(index);
	CHECK(effect(index).type == FFB_EFFECT_NONE);
	CHECK(effect(index).state == 0);
	CHECK(effect(index).magnitude == 0);
	CHECK(effect(index).filter[0] == nullptr);

	CHECK(host.allocateEffect(FFB_EFFECT_SINE) == index); // Block is reused
}

TEST_CASE_FIXTURE(FfbFixture, "block free with invalid index is ignored") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	host.blockFree(0);
	host.blockFree(MAX_EFFECTS + 1);
	host.blockFree(0xFF);
	CHECK(effect(index).type == FFB_EFFECT_CONSTANT);
}

TEST_CASE_FIXTURE(FfbFixture, "available ram pool decreases with allocated effects") {
	uint16_t effectSize = sizeof(FFB_Effect);
	host.createNewEffect(FFB_EFFECT_CONSTANT);
	CHECK(host.blockLoad().ramPoolAvailable == (uint16_t)((MAX_EFFECTS - 1) * effectSize));
	host.createNewEffect(FFB_EFFECT_CONSTANT);
	CHECK(host.blockLoad().ramPoolAvailable == (uint16_t)((MAX_EFFECTS - 2) * effectSize));
}

TEST_CASE_FIXTURE(FfbFixture, "available ram pool increases when effects are freed" *
		KNOWN_ISSUE("HidFFB::used_effects is never decremented. ramPoolAvailable shrinks with every created effect and underflows after MAX_EFFECTS allocations")) {
	uint16_t effectSize = sizeof(FFB_Effect);
	for (int i = 0; i < 3; i++) {
		uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
		host.blockFree(index);
	}
	host.createNewEffect(FFB_EFFECT_CONSTANT);
	CHECK(host.blockLoad().ramPoolAvailable == (uint16_t)((MAX_EFFECTS - 1) * effectSize));
}

TEST_CASE_FIXTURE(FfbFixture, "allocation sends a PID state report") {
	host.allocateEffect(FFB_EFFECT_CONSTANT);
	REQUIRE(HostUsb::state().hidReports.size() == 1);
	const HostUsb::HidReport &report = HostUsb::state().hidReports[0];
	REQUIRE(report.data.size() == 2);
	CHECK(report.data[0] == HID_ID_STATE);
	CHECK(report.data[1] == (HID_ACTUATOR_POWER | HID_EFFECT_PAUSE)); // FFB not active yet
}

// ---------------------------------------------------------------------------
// Set Effect report
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "set effect stores the effect parameters") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_SINE);
	PidHost::EffectParams params;
	params.duration = 1500;
	params.gain = 200;
	params.startDelay = 250;
	params.samplePeriod = 10;
	host.setEffect(index, FFB_EFFECT_SINE, params);

	FFB_Effect &fx = effect(index);
	CHECK(fx.type == FFB_EFFECT_SINE);
	CHECK(fx.duration == 1500);
	CHECK(fx.gain == 200);
	CHECK(fx.startDelay == 250);
	CHECK(fx.samplePeriod == 10);
	CHECK(fx.state == 0); // Set effect does not start the effect
}

TEST_CASE_FIXTURE(FfbFixture, "duration 0 is treated as infinite") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	PidHost::EffectParams params;
	params.duration = 0;
	host.setEffect(index, FFB_EFFECT_CONSTANT, params);
	CHECK(effect(index).duration == FFB_EFFECT_DURATION_INFINITE);
}

TEST_CASE_FIXTURE(FfbFixture, "set effect enables force feedback and reports the state") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	HostUsb::state().hidReports.clear();
	host.setEffect(index, FFB_EFFECT_CONSTANT);

	CHECK(ffb.getFfbActive());
	CHECK(ec->isActive());
	REQUIRE(HostUsb::state().hidReports.size() == 1);
	CHECK(HostUsb::state().hidReports[0].data[0] == HID_ID_STATE);
	CHECK(HostUsb::state().hidReports[0].data[1] == (HID_ACTUATOR_POWER | HID_ENABLE_ACTUATORS | HID_EFFECT_PLAYING));
}

TEST_CASE_FIXTURE(FfbFixture, "set effect with invalid block index is ignored") {
	PidHost::EffectParams params;
	host.setEffect(0, FFB_EFFECT_CONSTANT, params);
	host.setEffect(MAX_EFFECTS + 1, FFB_EFFECT_CONSTANT, params);
	CHECK_FALSE(ffb.getFfbActive());
	for (const FFB_Effect &fx : ec->effects) {
		CHECK(fx.type == FFB_EFFECT_NONE);
	}
}

TEST_CASE_FIXTURE(FfbFixture, "set effect accepts reports longer and shorter than the internal struct") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);

	// 2 axis descriptor: 4 more bytes for the type specific block offsets
	uint8_t longReport[sizeof(FFB_SetEffect_t) + 4] = {0};
	FFB_SetEffect_t report;
	report.effectBlockIndex = index;
	report.effectType = FFB_EFFECT_CONSTANT;
	report.gain = 99;
	report.enableAxis = PidHost::AXIS_X | PidHost::DIRECTION_ENABLE_2AXIS;
	report.directionX = 9000;
	std::memcpy(longReport, &report, sizeof(report));
	host.sendOutput(longReport, sizeof(longReport));
	CHECK(effect(index).gain == 99);
	CHECK(effect(index).axisMagnitudes[0] == Approx(1.0));

	// 1 axis descriptor: Only one direction
	report.gain = 55;
	uint8_t shortReport[sizeof(FFB_SetEffect_t) - 2];
	std::memcpy(shortReport, &report, sizeof(shortReport));
	host.sendOutput(shortReport, sizeof(shortReport));
	CHECK(effect(index).gain == 55);
}

// ---------------------------------------------------------------------------
// Axis magnitudes from the direction parameters
//
// PID 1.01: If Direction Enable is set the first direction instance is a polar angle
// and the force is distributed to the axes by the device. Otherwise the Axes Enable
// bits select the axes and the direction instances are used per axis.
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "characterization: axis magnitudes with direction enable (polar angle) on 2 axes") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	struct Case {
		uint16_t direction; // 0.01 degrees
		float x;
		float y;
	};
	// Current implementation: X = sin(angle), Y = -cos(angle)
	const Case cases[] = {
		{0, 0.0f, -1.0f},		 // north
		{4500, 0.7071f, -0.7071f},
		{9000, 1.0f, 0.0f},		 // east. Used by most games for a wheel
		{13500, 0.7071f, 0.7071f},
		{18000, 0.0f, 1.0f},	 // south
		{27000, -1.0f, 0.0f},	 // west
		{31500, -0.7071f, -0.7071f},
		{36000, 0.0f, -1.0f},
	};
	for (const Case &c : cases) {
		CAPTURE(c.direction);
		PidHost::EffectParams params;
		params.enableAxis = PidHost::DIRECTION_ENABLE_2AXIS;
		params.directionX = c.direction;
		params.directionY = 12345; // Not used with direction enable
		host.setEffect(index, FFB_EFFECT_CONSTANT, params);
		CHECK(effect(index).axisMagnitudes[0] == Approx(c.x).epsilon(0.001));
		CHECK(effect(index).axisMagnitudes[1] == Approx(c.y).epsilon(0.001));
	}
}

TEST_CASE_FIXTURE(FfbFixture, "characterization: axes enable bits are ignored with direction enable") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	for (uint8_t axesEnable : {(uint8_t)0, PidHost::AXIS_X, PidHost::AXIS_Y, (uint8_t)(PidHost::AXIS_X | PidHost::AXIS_Y)}) {
		CAPTURE(axesEnable);
		PidHost::EffectParams params;
		params.enableAxis = axesEnable | PidHost::DIRECTION_ENABLE_2AXIS;
		params.directionX = 9000;
		host.setEffect(index, FFB_EFFECT_CONSTANT, params);
		CHECK(effect(index).axisMagnitudes[0] == Approx(1.0).epsilon(0.001));
		CHECK(effect(index).axisMagnitudes[1] == Approx(0.0).epsilon(0.001));
	}
}

TEST_CASE_FIXTURE(FfbFixture, "characterization: axis magnitudes without direction enable (per axis direction)") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	struct Case {
		uint8_t axes;
		uint16_t directionX;
		uint16_t directionY;
		float x;
		float y;
	};
	// Current implementation: linear mapping X = (dir-18000)/18000, Y = -(dir-18000)/18000. 0 for disabled axes
	const uint8_t X = PidHost::AXIS_X, Y = PidHost::AXIS_Y;
	const Case cases[] = {
		{X, 0, 0, -1.0f, 0.0f},
		{X, 9000, 0, -0.5f, 0.0f},
		{X, 18000, 0, 0.0f, 0.0f},
		{X, 27000, 0, 0.5f, 0.0f},
		{X, 36000, 0, 1.0f, 0.0f},
		{Y, 0, 0, 0.0f, 1.0f},
		{Y, 0, 9000, 0.0f, 0.5f},
		{Y, 0, 18000, 0.0f, 0.0f},
		{Y, 0, 36000, 0.0f, -1.0f},
		{(uint8_t)(X | Y), 36000, 0, 1.0f, 1.0f},
		{(uint8_t)(X | Y), 27000, 27000, 0.5f, -0.5f},
		{0, 36000, 36000, 0.0f, 0.0f}, // No axis enabled
	};
	for (const Case &c : cases) {
		CAPTURE(c.axes);
		CAPTURE(c.directionX);
		CAPTURE(c.directionY);
		PidHost::EffectParams params;
		params.enableAxis = c.axes;
		params.directionX = c.directionX;
		params.directionY = c.directionY;
		host.setEffect(index, FFB_EFFECT_CONSTANT, params);
		CHECK(effect(index).axisMagnitudes[0] == Approx(c.x).epsilon(0.001));
		CHECK(effect(index).axisMagnitudes[1] == Approx(c.y).epsilon(0.001));
	}
}

TEST_CASE_FIXTURE(FfbFixture1Axis, "characterization: direction enable bit position depends on the axis count") {
	// With 1 axis the direction enable bit directly follows the X axis bit
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	PidHost::EffectParams params;
	params.enableAxis = PidHost::AXIS_X | PidHost::DIRECTION_ENABLE_1AXIS;
	params.directionX = 9000;
	host.setEffect(index, FFB_EFFECT_CONSTANT, params);
	CHECK(effect(index).axisMagnitudes[0] == Approx(1.0).epsilon(0.001));

	params.directionX = 27000;
	host.setEffect(index, FFB_EFFECT_CONSTANT, params);
	CHECK(effect(index).axisMagnitudes[0] == Approx(-1.0).epsilon(0.001));
}

TEST_CASE_FIXTURE(FfbFixture, "direction enable mask can be changed") {
	ffb.setDirectionEnableMask(PidHost::DIRECTION_ENABLE_1AXIS);
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	PidHost::EffectParams params;
	params.enableAxis = PidHost::AXIS_X | PidHost::DIRECTION_ENABLE_1AXIS;
	params.directionX = 9000;
	host.setEffect(index, FFB_EFFECT_CONSTANT, params);
	CHECK(effect(index).axisMagnitudes[0] == Approx(1.0).epsilon(0.001));
}

// ---------------------------------------------------------------------------
// Axis magnitudes of condition effects (spring, damper, inertia, friction)
//
// PID 1.01: With one condition block per axis the effect is not rotated. With a single
// condition block the direction of the Set Effect report defines the direction of the condition.
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "characterization: single condition block followed by set effect uses the effect direction") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_SPRING);
	host.setCondition(index, 0, 0, 10000, 10000, 10000, 10000, 0);
	PidHost::EffectParams params;
	params.enableAxis = PidHost::AXIS_X | PidHost::DIRECTION_ENABLE_2AXIS;
	params.directionX = 9000;
	host.setEffect(index, FFB_EFFECT_SPRING, params);

	CHECK(effect(index).useSingleCondition);
	CHECK(effect(index).axisMagnitudes[0] == Approx(1.0).epsilon(0.001));
	CHECK(effect(index).axisMagnitudes[1] == Approx(0.0).epsilon(0.001));
}

TEST_CASE_FIXTURE(FfbFixture, "characterization: condition block activates an axis with zero magnitude") {
	// Direction 0 results in X magnitude 0. A condition block received afterwards forces it to 1
	uint8_t index = host.allocateEffect(FFB_EFFECT_SPRING);
	PidHost::EffectParams params;
	params.enableAxis = PidHost::AXIS_X | PidHost::DIRECTION_ENABLE_2AXIS;
	params.directionX = 0;
	host.setEffect(index, FFB_EFFECT_SPRING, params);
	CHECK(effect(index).axisMagnitudes[0] == Approx(0.0).epsilon(0.001));

	host.setCondition(index, 0, 0, 10000, 10000, 10000, 10000, 0);
	CHECK(effect(index).axisMagnitudes[0] == Approx(1.0));
	CHECK(effect(index).axisMagnitudes[1] == Approx(-1.0).epsilon(0.001)); // From the direction
}

TEST_CASE_FIXTURE(FfbFixture, "characterization: the order of set effect and set condition changes the X magnitude for direction 0") {
	PidHost::EffectParams params;
	params.enableAxis = PidHost::AXIS_X | PidHost::DIRECTION_ENABLE_2AXIS;
	params.directionX = 0;

	uint8_t effectFirst = host.allocateEffect(FFB_EFFECT_SPRING);
	host.setEffect(effectFirst, FFB_EFFECT_SPRING, params);
	host.setCondition(effectFirst, 0, 0, 10000, 10000, 10000, 10000, 0);

	uint8_t conditionFirst = host.allocateEffect(FFB_EFFECT_SPRING);
	host.setCondition(conditionFirst, 0, 0, 10000, 10000, 10000, 10000, 0);
	host.setEffect(conditionFirst, FFB_EFFECT_SPRING, params);

	CHECK(effect(effectFirst).axisMagnitudes[0] == Approx(1.0));
	CHECK(effect(conditionFirst).axisMagnitudes[0] == Approx(0.0).epsilon(0.001)); // Spring has no effect on X
}

TEST_CASE_FIXTURE(FfbFixture, "characterization: two condition blocks enable both axes independent of the direction") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_SPRING);
	host.setCondition(index, 0, 0, 10000, 10000, 10000, 10000, 0);
	host.setCondition(index, 1, 0, 5000, 5000, 10000, 10000, 0);
	CHECK_FALSE(effect(index).useSingleCondition);

	PidHost::EffectParams params;
	params.enableAxis = PidHost::AXIS_X | PidHost::AXIS_Y | PidHost::DIRECTION_ENABLE_2AXIS;
	params.directionX = 4500; // Would rotate the effect
	host.setEffect(index, FFB_EFFECT_SPRING, params);

	CHECK(effect(index).axisMagnitudes[0] == Approx(1.0));
	CHECK(effect(index).axisMagnitudes[1] == Approx(1.0));
	CHECK(effect(index).conditions[0].positiveCoefficient == 10000);
	CHECK(effect(index).conditions[1].positiveCoefficient == 5000);
}

// ---------------------------------------------------------------------------
// Type specific parameter reports
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "set constant force stores the signed magnitude") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	host.setConstantForce(index, 12345);
	CHECK(effect(index).magnitude == 12345);
	host.setConstantForce(index, -32767);
	CHECK(effect(index).magnitude == -32767);
}

TEST_CASE_FIXTURE(FfbFixture, "set periodic stores magnitude, offset, phase and period") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_SINE);
	host.setPeriodic(index, 20000, -3000, 9000, 250);

	FFB_Effect &fx = effect(index);
	CHECK(fx.magnitude == 20000);
	CHECK(fx.offset == -3000);
	CHECK(fx.phase == 9000);
	CHECK(fx.period == 250);
}

TEST_CASE_FIXTURE(FfbFixture, "periodic period is limited to 1..32767 ms") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_SINE);
	host.setPeriodic(index, 1000, 0, 0, 0);
	CHECK(effect(index).period == 1);
	host.setPeriodic(index, 1000, 0, 0, 100000);
	CHECK(effect(index).period == 0x7fff);
}

TEST_CASE_FIXTURE(FfbFixture, "periodic phase covers the full range of the descriptor (0..359.99 degrees)" *
		KNOWN_ISSUE("FFB_Effect::phase is int16_t but the report value goes up to 35999. Phases above 327.67 degrees overflow to negative values")) {
	uint8_t index = host.allocateEffect(FFB_EFFECT_SINE);
	host.setPeriodic(index, 1000, 0, 35000, 100);
	CHECK((int32_t)effect(index).phase == 35000);
}

TEST_CASE_FIXTURE(FfbFixture, "set condition stores the parameters of each axis block") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_DAMPER);
	host.setCondition(index, 0, -100, 2000, -3000, 4000, 5000, 60);
	host.setCondition(index, 1, 100, 200, 300, 400, 500, 6);

	FFB_Effect_Condition &x = effect(index).conditions[0];
	CHECK(x.cpOffset == -100);
	CHECK(x.positiveCoefficient == 2000);
	CHECK(x.negativeCoefficient == -3000);
	CHECK(x.positiveSaturation == 4000);
	CHECK(x.negativeSaturation == 5000);
	CHECK(x.deadBand == 60);

	FFB_Effect_Condition &y = effect(index).conditions[1];
	CHECK(y.cpOffset == 100);
	CHECK(y.positiveCoefficient == 200);
	CHECK(y.negativeCoefficient == 300);
	CHECK(y.positiveSaturation == 400);
	CHECK(y.negativeSaturation == 500);
	CHECK(y.deadBand == 6);
}

TEST_CASE("condition is only active with a coefficient and its saturation") {
	FFB_Effect_Condition cond;
	CHECK_FALSE(cond.isActive());
	cond.positiveCoefficient = 100;
	CHECK_FALSE(cond.isActive()); // Characterization: Saturation 0 disables the condition
	cond.positiveSaturation = 100;
	CHECK(cond.isActive());
	cond = FFB_Effect_Condition();
	cond.negativeCoefficient = -100;
	cond.negativeSaturation = 100;
	CHECK(cond.isActive());
}

TEST_CASE_FIXTURE(FfbFixture, "set condition with a parameter block offset above the axis count does not corrupt the effect" *
		KNOWN_ISSUE_UB("HidFFB::set_condition limits the block offset to axisCount instead of axisCount-1 and writes conditions[MAX_AXIS] out of bounds. Reachable with offsets 2 and 3 which are valid in the report descriptor")) {
	uint8_t index = host.allocateEffect(FFB_EFFECT_SPRING);
	FFB_Effect &fx = effect(index);
	fx.phase = 1111;
	fx.period = 2222;
	fx.duration = 3333;
	fx.attackLevel = 4444;

	host.setCondition(index, 2, 0x5A5A, 0x5A5A, 0x5A5A, 0x5A5A, 0x5A5A, 0x5A5A);

	CHECK(fx.phase == 1111);
	CHECK(fx.period == 2222);
	CHECK(fx.duration == 3333);
	CHECK(fx.attackLevel == 4444);
}

TEST_CASE_FIXTURE(FfbFixture, "set envelope stores the envelope and enables it") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	CHECK_FALSE(effect(index).useEnvelope);
	host.setEnvelope(index, 1000, 2000, 300, 400);

	FFB_Effect &fx = effect(index);
	CHECK(fx.useEnvelope);
	CHECK(fx.attackLevel == 1000);
	CHECK(fx.fadeLevel == 2000);
	CHECK(fx.attackTime == 300);
	CHECK(fx.fadeTime == 400);
}

TEST_CASE_FIXTURE(FfbFixture, "set ramp stores start and end level") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_RAMP);
	host.setRamp(index, -10000, 20000);
	CHECK(effect(index).startLevel == -10000);
	CHECK(effect(index).endLevel == 20000);
	CHECK(effect(index).magnitude == 0x7fff);
}

TEST_CASE_FIXTURE(FfbFixture, "parameter reports with invalid block index are ignored") {
	for (uint8_t index : {(uint8_t)0, (uint8_t)(MAX_EFFECTS + 1), (uint8_t)0xFF}) {
		CAPTURE(index);
		host.setConstantForce(index, 1000);
		host.setPeriodic(index, 1000, 100, 100, 100);
		host.setCondition(index, 0, 1, 2, 3, 4, 5, 6);
		host.setEnvelope(index, 1, 2, 3, 4);
		host.setRamp(index, 1, 2);
		host.effectOperation(index, PidHost::OP_START);
	}
	for (const FFB_Effect &fx : ec->effects) {
		CHECK(fx.magnitude == 0);
		CHECK(fx.state == 0);
		CHECK_FALSE(fx.useEnvelope);
	}
}

TEST_CASE_FIXTURE(FfbFixture, "unknown and unsupported reports are ignored") {
	uint8_t custom[4] = {HID_ID_CSTMREP, 1, 2, 3};
	uint8_t sample[4] = {HID_ID_SMPLREP, 1, 2, 3};
	uint8_t unknown[4] = {0x7E, 1, 2, 3};
	host.sendOutput(custom, sizeof(custom));
	host.sendOutput(sample, sizeof(sample));
	host.sendOutput(unknown, sizeof(unknown));
	CHECK_FALSE(ffb.getFfbActive());
}

// ---------------------------------------------------------------------------
// Effect Operation report
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "effect operation starts and stops an effect") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	host.setEffect(index, FFB_EFFECT_CONSTANT);

	host.effectOperation(index, PidHost::OP_START);
	CHECK(effect(index).state == 1);
	host.effectOperation(index, PidHost::OP_STOP);
	CHECK(effect(index).state == 0);
}

TEST_CASE_FIXTURE(FfbFixture, "start records the start time including the start delay") {
	uint8_t index = host.allocateEffect(FFB_EFFECT_CONSTANT);
	PidHost::EffectParams params;
	params.startDelay = 250;
	host.setEffect(index, FFB_EFFECT_CONSTANT, params);

	HostPlatform::setTimeMs(1000);
	host.startEffect(index);
	CHECK(effect(index).startTime == 1250);
}

TEST_CASE_FIXTURE(FfbFixture, "restarting a running effect restarts its time") {
	uint8_t index = startEffect(FFB_EFFECT_SINE);
	HostPlatform::advanceMs(500);
	host.startEffect(index);
	CHECK(effect(index).startTime == 500);
	CHECK(effect(index).state == 1);
}

TEST_CASE_FIXTURE(FfbFixture, "start solo stops all other effects") {
	uint8_t a = startEffect(FFB_EFFECT_CONSTANT);
	uint8_t b = startEffect(FFB_EFFECT_SINE);
	uint8_t c = host.allocateEffect(FFB_EFFECT_SPRING);

	host.effectOperation(c, PidHost::OP_START_SOLO);
	CHECK(effect(a).state == 0);
	CHECK(effect(b).state == 0);
	CHECK(effect(c).state == 1);
}

// ---------------------------------------------------------------------------
// PID Device Control and Device Gain reports
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "device control enables and disables the actuators") {
	host.deviceControl(PidHost::DC_ENABLE_ACTUATORS);
	CHECK(ffb.getFfbActive());
	CHECK(ec->isActive());

	host.deviceControl(PidHost::DC_DISABLE_ACTUATORS);
	CHECK_FALSE(ffb.getFfbActive());
	CHECK_FALSE(ec->isActive());
}

TEST_CASE_FIXTURE(FfbFixture, "device control pause and continue") {
	uint8_t index = startEffect(FFB_EFFECT_CONSTANT);
	host.deviceControl(PidHost::DC_DEVICE_PAUSE);
	CHECK_FALSE(ffb.getFfbActive());
	CHECK(effect(index).state == 1); // Effects keep their state while paused

	host.deviceControl(PidHost::DC_DEVICE_CONTINUE);
	CHECK(ffb.getFfbActive());
	CHECK(effect(index).state == 1);
}

TEST_CASE_FIXTURE(FfbFixture, "device reset frees all effects and disables force feedback") {
	uint8_t a = startEffect(FFB_EFFECT_CONSTANT);
	uint8_t b = startEffect(FFB_EFFECT_SPRING);
	host.deviceControl(PidHost::DC_DEVICE_RESET);

	CHECK_FALSE(ffb.getFfbActive());
	CHECK(effect(a).type == FFB_EFFECT_NONE);
	CHECK(effect(b).type == FFB_EFFECT_NONE);
	CHECK(effect(a).state == 0);
	CHECK(host.allocateEffect(FFB_EFFECT_SINE) == 1);
}

TEST_CASE_FIXTURE(FfbFixture, "characterization: stop all effects disables force feedback but keeps the effects running") {
	uint8_t index = startEffect(FFB_EFFECT_CONSTANT);
	host.deviceControl(PidHost::DC_STOP_ALL_EFFECTS);
	CHECK_FALSE(ffb.getFfbActive());
	CHECK(effect(index).state == 1);
}

TEST_CASE_FIXTURE(FfbFixture, "stop all effects stops every running effect" *
		KNOWN_ISSUE("To be verified against PID 1.01 (DC Stop All Effects: issues a stop on every running effect). The firmware only disables the actuators. Effects resume after enable")) {
	uint8_t a = startEffect(FFB_EFFECT_CONSTANT);
	uint8_t b = startEffect(FFB_EFFECT_SINE);
	host.deviceControl(PidHost::DC_STOP_ALL_EFFECTS);
	CHECK(effect(a).state == 0);
	CHECK(effect(b).state == 0);
}

TEST_CASE_FIXTURE(FfbFixture, "device gain sets the global gain") {
	CHECK(ec->getGain() == 255);
	host.deviceGain(128);
	CHECK(ec->getGain() == 128);
	host.deviceGain(0);
	CHECK(ec->getGain() == 0);
}

// ---------------------------------------------------------------------------
// Update rate measurement
// ---------------------------------------------------------------------------

TEST_CASE_FIXTURE(FfbFixture, "report rate is measured") {
	uint8_t index = startEffect(FFB_EFFECT_CONSTANT);
	for (int i = 0; i < 50; i++) {
		HostPlatform::advanceMs(10);
		host.setConstantForce(index, i);
	}
	CHECK(ffb.getRate() == Approx(100).epsilon(0.05));
	CHECK(ffb.getConstantForceRate() == Approx(100).epsilon(0.05));

	// Rates drop to 0 after one second without reports
	HostPlatform::advanceMs(1001);
	CHECK(ffb.getRate() == 0);
	CHECK(ffb.getConstantForceRate() == 0);
}

TEST_CASE_FIXTURE(FfbFixture, "constant force rate only counts constant force reports") {
	uint8_t index = startEffect(FFB_EFFECT_SINE);
	for (int i = 0; i < 50; i++) {
		HostPlatform::advanceMs(10);
		host.setPeriodic(index, 1000, 0, 0, 100);
	}
	CHECK(ffb.getRate() == Approx(100).epsilon(0.05));
	CHECK(ffb.getConstantForceRate() == 0);
}

} // TEST_SUITE
