var hierarchy =
[
    [ "__attribute__", "struct____attribute____.html", null ],
    [ "__USBHS_COUNT0_t", "union_____u_s_b_h_s___c_o_u_n_t0__t.html", null ],
    [ "__USBHS_CSR0H_DEVICE_t", "union_____u_s_b_h_s___c_s_r0_h___d_e_v_i_c_e__t.html", null ],
    [ "__USBHS_CSR0H_HOST_t", "union_____u_s_b_h_s___c_s_r0_h___h_o_s_t__t.html", null ],
    [ "__USBHS_CSR0L_DEVICE_t", "union_____u_s_b_h_s___c_s_r0_l___d_e_v_i_c_e__t.html", null ],
    [ "__USBHS_CSR0L_HOST_t", "union_____u_s_b_h_s___c_s_r0_l___h_o_s_t__t.html", null ],
    [ "__USBHS_DEVCTL_t", "union_____u_s_b_h_s___d_e_v_c_t_l__t.html", null ],
    [ "__USBHS_DMACNTL_t", "union_____u_s_b_h_s___d_m_a_c_n_t_l__t.html", null ],
    [ "__USBHS_FADDR_t", "union_____u_s_b_h_s___f_a_d_d_r__t.html", null ],
    [ "__USBHS_FRAME_t", "union_____u_s_b_h_s___f_r_a_m_e__t.html", null ],
    [ "__USBHS_INDEX_t", "union_____u_s_b_h_s___i_n_d_e_x__t.html", null ],
    [ "__USBHS_INTRRXE_t", "union_____u_s_b_h_s___i_n_t_r_r_x_e__t.html", null ],
    [ "__USBHS_INTRTXE_t", "union_____u_s_b_h_s___i_n_t_r_t_x_e__t.html", null ],
    [ "__USBHS_INTRUSBE_t", "union_____u_s_b_h_s___i_n_t_r_u_s_b_e__t.html", null ],
    [ "__USBHS_POWER_t", "union_____u_s_b_h_s___p_o_w_e_r__t.html", null ],
    [ "__USBHS_RXCOUNT_t", "union_____u_s_b_h_s___r_x_c_o_u_n_t__t.html", null ],
    [ "__USBHS_RXCSRH_DEVICE_t", "union_____u_s_b_h_s___r_x_c_s_r_h___d_e_v_i_c_e__t.html", null ],
    [ "__USBHS_RXCSRH_HOST_t", "union_____u_s_b_h_s___r_x_c_s_r_h___h_o_s_t__t.html", null ],
    [ "__USBHS_RXCSRL_DEVICE_t", "union_____u_s_b_h_s___r_x_c_s_r_l___d_e_v_i_c_e__t.html", null ],
    [ "__USBHS_RXCSRL_HOST_t", "union_____u_s_b_h_s___r_x_c_s_r_l___h_o_s_t__t.html", null ],
    [ "__USBHS_RXFIFOADD_t", "union_____u_s_b_h_s___r_x_f_i_f_o_a_d_d__t.html", null ],
    [ "__USBHS_RXFUNCADDR_t", "union_____u_s_b_h_s___r_x_f_u_n_c_a_d_d_r__t.html", null ],
    [ "__USBHS_RXHUBADDR_t", "union_____u_s_b_h_s___r_x_h_u_b_a_d_d_r__t.html", null ],
    [ "__USBHS_RXHUBPORT_t", "union_____u_s_b_h_s___r_x_h_u_b_p_o_r_t__t.html", null ],
    [ "__USBHS_RXINTERVAL_t", "struct_____u_s_b_h_s___r_x_i_n_t_e_r_v_a_l__t.html", null ],
    [ "__USBHS_RXMAXP_t", "union_____u_s_b_h_s___r_x_m_a_x_p__t.html", null ],
    [ "__USBHS_RXTYPE_t", "union_____u_s_b_h_s___r_x_t_y_p_e__t.html", null ],
    [ "__USBHS_SOFTRST_t", "union_____u_s_b_h_s___s_o_f_t_r_s_t__t.html", null ],
    [ "__USBHS_TESTMODE_t", "union_____u_s_b_h_s___t_e_s_t_m_o_d_e__t.html", null ],
    [ "__USBHS_TXCSRH_DEVICE_t", "union_____u_s_b_h_s___t_x_c_s_r_h___d_e_v_i_c_e__t.html", null ],
    [ "__USBHS_TXCSRH_HOST_t", "union_____u_s_b_h_s___t_x_c_s_r_h___h_o_s_t__t.html", null ],
    [ "__USBHS_TXCSRL_DEVICE_t", "union_____u_s_b_h_s___t_x_c_s_r_l___d_e_v_i_c_e__t.html", null ],
    [ "__USBHS_TXCSRL_HOST_t", "union_____u_s_b_h_s___t_x_c_s_r_l___h_o_s_t__t.html", null ],
    [ "__USBHS_TXFIFOADD_t", "union_____u_s_b_h_s___t_x_f_i_f_o_a_d_d__t.html", null ],
    [ "__USBHS_TXFUNCADDR_t", "union_____u_s_b_h_s___t_x_f_u_n_c_a_d_d_r__t.html", null ],
    [ "__USBHS_TXHUBADDR_t", "union_____u_s_b_h_s___t_x_h_u_b_a_d_d_r__t.html", null ],
    [ "__USBHS_TXHUBPORT_t", "union_____u_s_b_h_s___t_x_h_u_b_p_o_r_t__t.html", null ],
    [ "__USBHS_TXINTERVAL_t", "struct_____u_s_b_h_s___t_x_i_n_t_e_r_v_a_l__t.html", null ],
    [ "__USBHS_TXMAXP_t", "union_____u_s_b_h_s___t_x_m_a_x_p__t.html", null ],
    [ "__USBHS_TXTYPE_t", "union_____u_s_b_h_s___t_x_t_y_p_e__t.html", null ],
    [ "__USBHS_TYPE0_t", "union_____u_s_b_h_s___t_y_p_e0__t.html", null ],
    [ "_ccrx_evenaccess", "struct__ccrx__evenaccess.html", null ],
    [ "AdcHandler", "class_adc_handler.html", null ],
    [ "AnalogAxisProcessing", "class_analog_axis_processing.html", [
      [ "ADS111X_AnalogSource", "class_a_d_s111_x___analog_source.html", null ],
      [ "LocalAnalog", "class_local_analog.html", null ]
    ] ],
    [ "AnalogProcessingConfig", "struct_analog_processing_config.html", null ],
    [ "AnalogAxisProcessing::AnalogProcessingMode", "struct_analog_axis_processing_1_1_analog_processing_mode.html", null ],
    [ "audio_feedback_params_t", "structaudio__feedback__params__t.html", null ],
    [ "audiod_function_t", "structaudiod__function__t.html", null ],
    [ "AxesManager", "class_axes_manager.html", null ],
    [ "axis_metric_t", "structaxis__metric__t.html", null ],
    [ "AxisConfig", "struct_axis_config.html", null ],
    [ "AxisFlashAddrs", "struct_axis_flash_addrs.html", null ],
    [ "Biquad", "class_biquad.html", null ],
    [ "biquad_constant_t", "structbiquad__constant__t.html", null ],
    [ "btd_interface_t", "structbtd__interface__t.html", null ],
    [ "ButtonSourceConfig", "struct_button_source_config.html", null ],
    [ "CAN_Config_t", "struct_c_a_n___config__t.html", null ],
    [ "CAN_filter", "struct_c_a_n__filter.html", null ],
    [ "CAN_msg_header_rx", "class_c_a_n__msg__header__rx.html", null ],
    [ "CAN_msg_header_tx", "struct_c_a_n__msg__header__tx.html", null ],
    [ "CAN_rx_msg", "struct_c_a_n__rx__msg.html", null ],
    [ "CAN_tx_msg", "struct_c_a_n__tx__msg.html", null ],
    [ "CanHandler", "class_can_handler.html", [
      [ "CANPort_2B", "class_c_a_n_port__2_b.html", null ],
      [ "CanAnalogBase", "class_can_analog_base.html", [
        [ "CanAnalog< AMOUNT >", "class_can_analog.html", null ]
      ] ],
      [ "CanBridge", "class_can_bridge.html", null ],
      [ "CanButtons", "class_can_buttons.html", null ],
      [ "ODriveCAN", "class_o_drive_c_a_n.html", [
        [ "ODriveCAN1", "class_o_drive_c_a_n1.html", null ],
        [ "ODriveCAN2", "class_o_drive_c_a_n2.html", null ]
      ] ],
      [ "RmdMotorCAN", "class_rmd_motor_c_a_n.html", [
        [ "RmdMotorCAN1", "class_rmd_motor_c_a_n1.html", null ],
        [ "RmdMotorCAN2", "class_rmd_motor_c_a_n2.html", null ]
      ] ],
      [ "VescCAN", "class_vesc_c_a_n.html", [
        [ "VESC_1", "class_v_e_s_c__1.html", null ],
        [ "VESC_2", "class_v_e_s_c__2.html", null ]
      ] ]
    ] ],
    [ "CANPortHardwareConfig", "class_c_a_n_port_hardware_config.html", null ],
    [ "CDCcomm", "class_c_d_ccomm.html", null ],
    [ "cdcd_interface_t", "structcdcd__interface__t.html", null ],
    [ "cdch_interface_t", "structcdch__interface__t.html", null ],
    [ "cdch_serial_driver_t", "structcdch__serial__driver__t.html", null ],
    [ "ChoosableClass", "class_choosable_class.html", [
      [ "AnalogSource", "class_analog_source.html", [
        [ "ADS111X_AnalogSource", "class_a_d_s111_x___analog_source.html", null ],
        [ "CanAnalogBase", "class_can_analog_base.html", null ],
        [ "LocalAnalog", "class_local_analog.html", null ]
      ] ],
      [ "ButtonSource", "class_button_source.html", [
        [ "CanButtons", "class_can_buttons.html", null ],
        [ "LocalButtons", "class_local_buttons.html", null ],
        [ "PCF8574Buttons", "class_p_c_f8574_buttons.html", null ],
        [ "SPI_Buttons", "class_s_p_i___buttons.html", [
          [ "SPI_Buttons_1", "class_s_p_i___buttons__1.html", null ],
          [ "SPI_Buttons_2", "class_s_p_i___buttons__2.html", null ]
        ] ],
        [ "ShifterAnalog", "class_shifter_analog.html", null ]
      ] ],
      [ "Encoder", "class_encoder.html", [
        [ "EncoderBissC", "class_encoder_biss_c.html", null ],
        [ "EncoderLocal", "class_encoder_local.html", null ],
        [ "EncoderSSI", "class_encoder_s_s_i.html", null ],
        [ "MotorSimplemotion", "class_motor_simplemotion.html", [
          [ "MotorSimplemotion1", "class_motor_simplemotion1.html", null ],
          [ "MotorSimplemotion2", "class_motor_simplemotion2.html", null ]
        ] ],
        [ "MtEncoderSPI", "class_mt_encoder_s_p_i.html", null ],
        [ "ODriveCAN", "class_o_drive_c_a_n.html", null ],
        [ "RmdMotorCAN", "class_rmd_motor_c_a_n.html", null ],
        [ "TMC4671", "class_t_m_c4671.html", [
          [ "TMC_1", "class_t_m_c__1.html", null ],
          [ "TMC_2", "class_t_m_c__2.html", null ]
        ] ],
        [ "VescCAN", "class_vesc_c_a_n.html", null ]
      ] ],
      [ "FFBoardMain", "class_f_f_board_main.html", [
        [ "CanBridge", "class_can_bridge.html", null ],
        [ "CustomMain", "class_custom_main.html", null ],
        [ "FFBHIDMain", "class_f_f_b_h_i_d_main.html", [
          [ "FFBHIDExt", "class_f_f_b_h_i_d_ext.html", null ],
          [ "FFBJoystick", "class_f_f_b_joystick.html", null ],
          [ "FFBWheel", "class_f_f_b_wheel.html", null ]
        ] ],
        [ "MidiMain", "class_midi_main.html", null ],
        [ "TMCDebugBridge", "class_t_m_c_debug_bridge.html", null ]
      ] ],
      [ "MotorDriver", "class_motor_driver.html", [
        [ "MotorPWM", "class_motor_p_w_m.html", null ],
        [ "MotorSimplemotion", "class_motor_simplemotion.html", null ],
        [ "ODriveCAN", "class_o_drive_c_a_n.html", null ],
        [ "RmdMotorCAN", "class_rmd_motor_c_a_n.html", null ],
        [ "TMC4671", "class_t_m_c4671.html", null ],
        [ "VescCAN", "class_vesc_c_a_n.html", null ]
      ] ]
    ] ],
    [ "ci_fs_controller_t", "structci__fs__controller__t.html", null ],
    [ "ci_fs_regs_t", "structci__fs__regs__t.html", null ],
    [ "ci_hs_controller_t", "structci__hs__controller__t.html", null ],
    [ "ci_hs_regs_t", "structci__hs__regs__t.html", null ],
    [ "class_entry< B >", "structclass__entry.html", null ],
    [ "ClassChooser< T >", "class_class_chooser.html", null ],
    [ "ClassIdentifier", "struct_class_identifier.html", null ],
    [ "CmdHandlerCommanddef", "class_cmd_handler_commanddef.html", null ],
    [ "CmdHandlerInfo", "struct_cmd_handler_info.html", null ],
    [ "CmdParser", "class_cmd_parser.html", null ],
    [ "CommandHandler", "class_command_handler.html", [
      [ "ADS111X_AnalogSource", "class_a_d_s111_x___analog_source.html", null ],
      [ "Axis", "class_axis.html", null ],
      [ "CANPort_2B", "class_c_a_n_port__2_b.html", null ],
      [ "CanAnalogBase", "class_can_analog_base.html", null ],
      [ "CanButtons", "class_can_buttons.html", null ],
      [ "EffectsCalculator", "class_effects_calculator.html", null ],
      [ "EncoderBissC", "class_encoder_biss_c.html", null ],
      [ "EncoderLocal", "class_encoder_local.html", null ],
      [ "EncoderSSI", "class_encoder_s_s_i.html", null ],
      [ "FFBoardMain", "class_f_f_board_main.html", null ],
      [ "I2CPort", "class_i2_c_port.html", null ],
      [ "LocalAnalog", "class_local_analog.html", null ],
      [ "LocalButtons", "class_local_buttons.html", null ],
      [ "MotorPWM", "class_motor_p_w_m.html", null ],
      [ "MotorSimplemotion", "class_motor_simplemotion.html", null ],
      [ "MtEncoderSPI", "class_mt_encoder_s_p_i.html", null ],
      [ "ODriveCAN", "class_o_drive_c_a_n.html", null ],
      [ "PCF8574Buttons", "class_p_c_f8574_buttons.html", null ],
      [ "RmdMotorCAN", "class_rmd_motor_c_a_n.html", null ],
      [ "SPI_Buttons", "class_s_p_i___buttons.html", null ],
      [ "SerialFFB", "class_serial_f_f_b.html", null ],
      [ "ShifterAnalog", "class_shifter_analog.html", null ],
      [ "SystemCommands", "class_system_commands.html", null ],
      [ "TMC4671", "class_t_m_c4671.html", null ],
      [ "VescCAN", "class_vesc_c_a_n.html", null ]
    ] ],
    [ "CommandInterface", "class_command_interface.html", [
      [ "HID_CommandInterface", "class_h_i_d___command_interface.html", null ],
      [ "StringCommandInterface", "class_string_command_interface.html", [
        [ "CDC_CommandInterface", "class_c_d_c___command_interface.html", null ],
        [ "UART_CommandInterface", "class_u_a_r_t___command_interface.html", null ]
      ] ]
    ] ],
    [ "CommandReply", "class_command_reply.html", null ],
    [ "CommandResult", "struct_command_result.html", null ],
    [ "cpp_freertos::ConditionVariable", "classcpp__freertos_1_1_condition_variable.html", null ],
    [ "Control_t", "struct_control__t.html", null ],
    [ "cpp_freertos::CriticalSection", "classcpp__freertos_1_1_critical_section.html", null ],
    [ "da146xx_dma_channel_t", "structda146xx__dma__channel__t.html", null ],
    [ "dcd_data_t", "structdcd__data__t.html", null ],
    [ "dcd_qhd_t", "structdcd__qhd__t.html", null ],
    [ "dcd_qtd_t", "structdcd__qtd__t.html", null ],
    [ "dcd_registers_t", "structdcd__registers__t.html", null ],
    [ "devdma_t", "structdevdma__t.html", null ],
    [ "dfu_state_ctx_t", "structdfu__state__ctx__t.html", null ],
    [ "dma_desc_t", "structdma__desc__t.html", null ],
    [ "dwc2_channel_t", "structdwc2__channel__t.html", null ],
    [ "dwc2_dep_t", "structdwc2__dep__t.html", null ],
    [ "dwc2_epin_t", "structdwc2__epin__t.html", null ],
    [ "dwc2_epout_t", "structdwc2__epout__t.html", null ],
    [ "dwc2_regs_t", "structdwc2__regs__t.html", null ],
    [ "ecm_notify_struct", "structecm__notify__struct.html", null ],
    [ "effect_biquad_t", "structeffect__biquad__t.html", null ],
    [ "effect_gain_t", "structeffect__gain__t.html", null ],
    [ "effect_scaler_t", "structeffect__scaler__t.html", null ],
    [ "effect_stat_t", "structeffect__stat__t.html", null ],
    [ "EffectsControlItf", "class_effects_control_itf.html", [
      [ "HidFFB", "class_hid_f_f_b.html", null ],
      [ "SerialFFB", "class_serial_f_f_b.html", null ]
    ] ],
    [ "ehci_cap_registers_t", "structehci__cap__registers__t.html", null ],
    [ "ehci_data_t", "structehci__data__t.html", null ],
    [ "ehci_link_t", "unionehci__link__t.html", null ],
    [ "ehci_qtd_t", "structehci__qtd__t.html", null ],
    [ "ehci_registers_t", "structehci__registers__t.html", null ],
    [ "ep_alloc_t", "structep__alloc__t.html", null ],
    [ "Error", "class_error.html", null ],
    [ "ErrorHandler", "class_error_handler.html", [
      [ "Axis", "class_axis.html", null ],
      [ "ErrorPrinter", "class_error_printer.html", null ],
      [ "FFBHIDMain", "class_f_f_b_h_i_d_main.html", null ]
    ] ],
    [ "ErrorHandlerifdef TIM_TMC", null, [
      [ "TMC4671", "class_t_m_c4671.html", null ]
    ] ],
    [ "RmdMotorCAN::ErrorStatus::ErrorStatur_s", "struct_rmd_motor_c_a_n_1_1_error_status_1_1_error_statur__s.html", null ],
    [ "RmdMotorCAN::ErrorStatus", "union_rmd_motor_c_a_n_1_1_error_status.html", null ],
    [ "cpp_freertos::EventGroup", "classcpp__freertos_1_1_event_group.html", null ],
    [ "std::exception", null, [
      [ "cpp_freertos::EventGroupCreateException", "classcpp__freertos_1_1_event_group_create_exception.html", null ],
      [ "cpp_freertos::MemoryPoolBadAlignmentException", "classcpp__freertos_1_1_memory_pool_bad_alignment_exception.html", null ],
      [ "cpp_freertos::MemoryPoolMallocException", "classcpp__freertos_1_1_memory_pool_malloc_exception.html", null ],
      [ "cpp_freertos::MutexCreateException", "classcpp__freertos_1_1_mutex_create_exception.html", null ],
      [ "cpp_freertos::QueueCreateException", "classcpp__freertos_1_1_queue_create_exception.html", null ],
      [ "cpp_freertos::ReadWriteLockCreateException", "classcpp__freertos_1_1_read_write_lock_create_exception.html", null ],
      [ "cpp_freertos::SemaphoreCreateException", "classcpp__freertos_1_1_semaphore_create_exception.html", null ],
      [ "cpp_freertos::TaskletCreateException", "classcpp__freertos_1_1_tasklet_create_exception.html", null ],
      [ "cpp_freertos::TimerCreateException", "classcpp__freertos_1_1_timer_create_exception.html", null ]
    ] ],
    [ "ExtiHandler", "class_exti_handler.html", [
      [ "EncoderLocal", "class_encoder_local.html", null ],
      [ "FFBHIDMain", "class_f_f_b_h_i_d_main.html", null ],
      [ "TMC4671", "class_t_m_c4671.html", null ]
    ] ],
    [ "FastAvg< T, LEN >", "class_fast_avg.html", null ],
    [ "FastMovingAverage< T >", "class_fast_moving_average.html", null ],
    [ "FFB_Effect", "struct_f_f_b___effect.html", null ],
    [ "FFB_Effect_Condition", "struct_f_f_b___effect___condition.html", null ],
    [ "free_block_t", "structfree__block__t.html", null ],
    [ "fsdev_btable_t", "unionfsdev__btable__t.html", null ],
    [ "fsdev_pma_buf_t", "structfsdev__pma__buf__t.html", null ],
    [ "fsdev_regs_t", "structfsdev__regs__t.html", null ],
    [ "ft9xx_xfer_state", "structft9xx__xfer__state.html", null ],
    [ "GearRatio_t", "struct_gear_ratio__t.html", null ],
    [ "GpioPin", "class_gpio_pin.html", [
      [ "InputPin", "class_input_pin.html", null ],
      [ "OutputPin", "class_output_pin.html", null ]
    ] ],
    [ "gtd_extra_data_t", "structgtd__extra__data__t.html", null ],
    [ "hcd_data_t", "structhcd__data__t.html", null ],
    [ "hcd_devtree_info_t", "structhcd__devtree__info__t.html", null ],
    [ "hcd_endpoint_t", "structhcd__endpoint__t.html", null ],
    [ "hcd_event_t", "structhcd__event__t.html", null ],
    [ "hcd_xfer_t", "structhcd__xfer__t.html", null ],
    [ "hidd_interface_t", "structhidd__interface__t.html", null ],
    [ "hidh_interface_t", "structhidh__interface__t.html", null ],
    [ "HS_PHYC_GlobalTypeDef", "struct_h_s___p_h_y_c___global_type_def.html", null ],
    [ "hstdma_t", "structhstdma__t.html", null ],
    [ "hub_interface_t", "structhub__interface__t.html", null ],
    [ "hub_port_status_response_t", "structhub__port__status__response__t.html", null ],
    [ "hub_status_response_t", "structhub__status__response__t.html", null ],
    [ "hw_endpoint", "structhw__endpoint.html", null ],
    [ "hw_fifo_t", "unionhw__fifo__t.html", null ],
    [ "I2CDevice", "class_i2_c_device.html", [
      [ "ADS111X", "class_a_d_s111_x.html", [
        [ "ADS111X_AnalogSource", "class_a_d_s111_x___analog_source.html", null ]
      ] ],
      [ "PCF8574", "class_p_c_f8574.html", [
        [ "PCF8574Buttons", "class_p_c_f8574_buttons.html", null ]
      ] ]
    ] ],
    [ "I2CHandler", "class_i2_c_handler.html", [
      [ "I2CPort", "class_i2_c_port.html", null ]
    ] ],
    [ "I2CPortHardwareConfig", "class_i2_c_port_hardware_config.html", null ],
    [ "I2CPortHardwareConfig::I2CPortHardwareConfig_preset", "struct_i2_c_port_hardware_config_1_1_i2_c_port_hardware_config__preset.html", null ],
    [ "Ledstruct", "struct_ledstruct.html", null ],
    [ "ctypes.LittleEndianStructure", null, [
      [ "dwc2_info.GHWCFG2", "classdwc2__info_1_1_g_h_w_c_f_g2.html", null ],
      [ "dwc2_info.GHWCFG3", "classdwc2__info_1_1_g_h_w_c_f_g3.html", null ],
      [ "dwc2_info.GHWCFG4", "classdwc2__info_1_1_g_h_w_c_f_g4.html", null ]
    ] ],
    [ "LocalAnalogConfig", "struct_local_analog_config.html", null ],
    [ "cpp_freertos::LockGuard", "classcpp__freertos_1_1_lock_guard.html", null ],
    [ "max3421_data_t", "structmax3421__data__t.html", null ],
    [ "max3421_ep_t", "structmax3421__ep__t.html", null ],
    [ "cpp_freertos::MemoryPool", "classcpp__freertos_1_1_memory_pool.html", null ],
    [ "metric_t", "structmetric__t.html", null ],
    [ "midid_interface_t", "structmidid__interface__t.html", null ],
    [ "midid_stream_t", "structmidid__stream__t.html", null ],
    [ "MidiHandler", "class_midi_handler.html", [
      [ "MidiMain", "class_midi_main.html", null ]
    ] ],
    [ "MidiNote", "struct_midi_note.html", null ],
    [ "MinMaxPair", "struct_min_max_pair.html", null ],
    [ "mscd_interface_t", "structmscd__interface__t.html", null ],
    [ "msch_interface_t", "structmsch__interface__t.html", null ],
    [ "cpp_freertos::Mutex", "classcpp__freertos_1_1_mutex.html", [
      [ "cpp_freertos::MutexRecursive", "classcpp__freertos_1_1_mutex_recursive.html", null ],
      [ "cpp_freertos::MutexStandard", "classcpp__freertos_1_1_mutex_standard.html", null ]
    ] ],
    [ "ncm_interface_t", "structncm__interface__t.html", null ],
    [ "ncm_notify_t", "structncm__notify__t.html", null ],
    [ "netd_interface_t", "structnetd__interface__t.html", null ],
    [ "ohci_hcca_t", "structohci__hcca__t.html", null ],
    [ "ohci_registers_t", "structohci__registers__t.html", null ],
    [ "osal_queue_def_t", "structosal__queue__def__t.html", null ],
    [ "osal_semaphore_def_t", "structosal__semaphore__def__t.html", null ],
    [ "ParsedCommand", "struct_parsed_command.html", null ],
    [ "PersistentStorage", "class_persistent_storage.html", [
      [ "AnalogSource", "class_analog_source.html", null ],
      [ "Axis", "class_axis.html", null ],
      [ "ButtonSource", "class_button_source.html", null ],
      [ "CANPort", "class_c_a_n_port.html", [
        [ "CANPort_2B", "class_c_a_n_port__2_b.html", null ]
      ] ],
      [ "EffectsCalculator", "class_effects_calculator.html", null ],
      [ "EncoderBissC", "class_encoder_biss_c.html", null ],
      [ "EncoderLocal", "class_encoder_local.html", null ],
      [ "EncoderSSI", "class_encoder_s_s_i.html", null ],
      [ "FFBHIDMain", "class_f_f_b_h_i_d_main.html", null ],
      [ "I2CPort", "class_i2_c_port.html", null ],
      [ "MotorPWM", "class_motor_p_w_m.html", null ],
      [ "MtEncoderSPI", "class_mt_encoder_s_p_i.html", null ],
      [ "ODriveCAN", "class_o_drive_c_a_n.html", null ],
      [ "RmdMotorCAN", "class_rmd_motor_c_a_n.html", null ],
      [ "TMC4671", "class_t_m_c4671.html", null ],
      [ "VescCAN", "class_vesc_c_a_n.html", null ]
    ] ],
    [ "pipe_state_t", "structpipe__state__t.html", null ],
    [ "CANPortHardwareConfig::PresetEntry", "struct_c_a_n_port_hardware_config_1_1_preset_entry.html", null ],
    [ "PWMConfig", "struct_p_w_m_config.html", null ],
    [ "cpp_freertos::Queue", "classcpp__freertos_1_1_queue.html", [
      [ "cpp_freertos::BinaryQueue", "classcpp__freertos_1_1_binary_queue.html", null ],
      [ "cpp_freertos::Deque", "classcpp__freertos_1_1_deque.html", null ]
    ] ],
    [ "cpp_freertos::ReadWriteLock", "classcpp__freertos_1_1_read_write_lock.html", [
      [ "cpp_freertos::ReadWriteLockPreferReader", "classcpp__freertos_1_1_read_write_lock_prefer_reader.html", null ],
      [ "cpp_freertos::ReadWriteLockPreferWriter", "classcpp__freertos_1_1_read_write_lock_prefer_writer.html", null ]
    ] ],
    [ "RingBuffer", "struct_ring_buffer.html", null ],
    [ "RingBufferWrapper", "class_ring_buffer_wrapper.html", null ],
    [ "rndis_msg_initialize_cmplt_t", "structrndis__msg__initialize__cmplt__t.html", null ],
    [ "rndis_msg_initialize_t", "structrndis__msg__initialize__t.html", null ],
    [ "rndis_msg_keep_alive_t", "structrndis__msg__keep__alive__t.html", null ],
    [ "rndis_msg_out_of_band_data_t", "structrndis__msg__out__of__band__data__t.html", null ],
    [ "rndis_msg_packet_t", "structrndis__msg__packet__t.html", null ],
    [ "rndis_msg_query_cmplt_t", "structrndis__msg__query__cmplt__t.html", null ],
    [ "rndis_msg_query_t", "structrndis__msg__query__t.html", null ],
    [ "rndis_msg_reset_cmplt_t", "structrndis__msg__reset__cmplt__t.html", null ],
    [ "rndis_msg_reset_t", "structrndis__msg__reset__t.html", null ],
    [ "rndis_msg_set_cmplt_t", "structrndis__msg__set__cmplt__t.html", null ],
    [ "rusb2_controller_t", "structrusb2__controller__t.html", null ],
    [ "RUSB2_PIPE_TR_t", "struct_r_u_s_b2___p_i_p_e___t_r__t.html", null ],
    [ "scsi_read_capacity10_resp_t", "structscsi__read__capacity10__resp__t.html", null ],
    [ "cpp_freertos::Semaphore", "classcpp__freertos_1_1_semaphore.html", [
      [ "cpp_freertos::BinarySemaphore", "classcpp__freertos_1_1_binary_semaphore.html", null ],
      [ "cpp_freertos::CountingSemaphore", "classcpp__freertos_1_1_counting_semaphore.html", null ]
    ] ],
    [ "Singleton< T >", "class_singleton.html", null ],
    [ "MotorSimplemotion::Sm2FastUpdate", "struct_motor_simplemotion_1_1_sm2_fast_update.html", null ],
    [ "MotorSimplemotion::Sm2FastUpdate_reply", "struct_motor_simplemotion_1_1_sm2_fast_update__reply.html", null ],
    [ "SPIConfig", "struct_s_p_i_config.html", null ],
    [ "SPIDevice", "class_s_p_i_device.html", [
      [ "EncoderBissC", "class_encoder_biss_c.html", null ],
      [ "EncoderSSI", "class_encoder_s_s_i.html", null ],
      [ "MtEncoderSPI", "class_mt_encoder_s_p_i.html", null ],
      [ "SPI_Buttons", "class_s_p_i___buttons.html", null ],
      [ "ShifterAnalog::G27ShifterButtonClient", "class_shifter_analog_1_1_g27_shifter_button_client.html", null ],
      [ "TMC4671", "class_t_m_c4671.html", null ]
    ] ],
    [ "SpiHandler", "class_spi_handler.html", [
      [ "SPIPort", "class_s_p_i_port.html", null ]
    ] ],
    [ "StatusFlags", "union_status_flags.html", null ],
    [ "StatusFlags::StatusFlags_s", "struct_status_flags_1_1_status_flags__s.html", null ],
    [ "cpp_freertos::Tasklet", "classcpp__freertos_1_1_tasklet.html", null ],
    [ "cpp_freertos::Thread", "classcpp__freertos_1_1_thread.html", [
      [ "ADS111X_AnalogSource", "class_a_d_s111_x___analog_source.html", null ],
      [ "CDC_CommandInterface", "class_c_d_c___command_interface.html", null ],
      [ "EffectsCalculator", "class_effects_calculator.html", null ],
      [ "EncoderBissC", "class_encoder_biss_c.html", null ],
      [ "ErrorPrinter", "class_error_printer.html", null ],
      [ "FFBHIDMain", "class_f_f_b_h_i_d_main.html", null ],
      [ "FFBoardMainCommandThread", "class_f_f_board_main_command_thread.html", null ],
      [ "HID_CommandInterface", "class_h_i_d___command_interface.html", null ],
      [ "MtEncoderSPI", "class_mt_encoder_s_p_i.html", null ],
      [ "ODriveCAN", "class_o_drive_c_a_n.html", null ],
      [ "PCF8574Buttons", "class_p_c_f8574_buttons.html", null ],
      [ "RmdMotorCAN", "class_rmd_motor_c_a_n.html", null ],
      [ "TMC4671", "class_t_m_c4671.html", null ],
      [ "TMC4671::TMC_ExternalEncoderUpdateThread", "class_t_m_c4671_1_1_t_m_c___external_encoder_update_thread.html", null ],
      [ "UART_CommandInterface", "class_u_a_r_t___command_interface.html", null ],
      [ "USBdevice", "class_u_s_bdevice.html", null ],
      [ "VescCAN", "class_vesc_c_a_n.html", null ],
      [ "cpp_freertos::WorkQueue::CWorkerThread", "classcpp__freertos_1_1_work_queue_1_1_c_worker_thread.html", null ]
    ] ],
    [ "cpp_freertos::TickHook", "classcpp__freertos_1_1_tick_hook.html", null ],
    [ "cpp_freertos::Ticks", "classcpp__freertos_1_1_ticks.html", null ],
    [ "cpp_freertos::Timer", "classcpp__freertos_1_1_timer.html", null ],
    [ "TimerHandler", "class_timer_handler.html", [
      [ "EncoderLocal", "class_encoder_local.html", null ],
      [ "MidiMain", "class_midi_main.html", null ]
    ] ],
    [ "TimerHandlerendif", null, [
      [ "TMC4671", "class_t_m_c4671.html", null ]
    ] ],
    [ "TMC4671ABNConf", "struct_t_m_c4671_a_b_n_conf.html", null ],
    [ "TMC4671AENCConf", "struct_t_m_c4671_a_e_n_c_conf.html", null ],
    [ "TMC4671Biquad", "class_t_m_c4671_biquad.html", null ],
    [ "TMC4671Biquad_conf", "struct_t_m_c4671_biquad__conf.html", null ],
    [ "TMC4671Biquad_t", "struct_t_m_c4671_biquad__t.html", null ],
    [ "TMC4671BiquadFilters", "struct_t_m_c4671_biquad_filters.html", null ],
    [ "TMC4671FlashAddrs", "struct_t_m_c4671_flash_addrs.html", null ],
    [ "TMC4671HALLConf", "struct_t_m_c4671_h_a_l_l_conf.html", null ],
    [ "TMC4671HardwareTypeConf", "struct_t_m_c4671_hardware_type_conf.html", null ],
    [ "TMC4671Limits", "struct_t_m_c4671_limits.html", null ],
    [ "TMC4671MainConfig", "struct_t_m_c4671_main_config.html", null ],
    [ "TMC4671MotConf", "struct_t_m_c4671_mot_conf.html", null ],
    [ "TMC4671PIDConf", "struct_t_m_c4671_p_i_d_conf.html", null ],
    [ "TMC4671PidPrecision", "struct_t_m_c4671_pid_precision.html", null ],
    [ "hcd_endpoint_t::TU_ATTR_PACKED", "structhcd__endpoint__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "hcd_xfer_t::TU_ATTR_PACKED", "structhcd__xfer__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "max3421_ep_t::TU_ATTR_PACKED", "structmax3421__ep__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "TU_ATTR_PACKED", "struct_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "TU_ATTR_PACKED::TU_ATTR_PACKED", "struct_t_u___a_t_t_r___p_a_c_k_e_d_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "tu_edpt_stream_t::TU_ATTR_PACKED", "structtu__edpt__stream__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "tu_fifo_t::TU_ATTR_PACKED", "structtu__fifo__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "tusb_desc_cs_video_fmt_t::TU_ATTR_PACKED", "structtusb__desc__cs__video__fmt__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "tusb_desc_cs_video_frm_t::TU_ATTR_PACKED", "structtusb__desc__cs__video__frm__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "usbd_device_t::TU_ATTR_PACKED", "structusbd__device__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "usbh_dev0_t::TU_ATTR_PACKED", "structusbh__dev0__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "usbh_device_t::TU_ATTR_PACKED", "structusbh__device__t_1_1_t_u___a_t_t_r___p_a_c_k_e_d.html", null ],
    [ "tu_edpt_stream_t", "structtu__edpt__stream__t.html", null ],
    [ "tu_fifo_buffer_info_t", "structtu__fifo__buffer__info__t.html", null ],
    [ "tu_fifo_t", "structtu__fifo__t.html", null ],
    [ "tu_lookup_entry_t", "structtu__lookup__entry__t.html", null ],
    [ "tu_lookup_table_t", "structtu__lookup__table__t.html", null ],
    [ "tuh_configure_max3421_t", "structtuh__configure__max3421__t.html", null ],
    [ "tuh_configure_param_t", "uniontuh__configure__param__t.html", null ],
    [ "tuh_hid_report_info_t", "structtuh__hid__report__info__t.html", null ],
    [ "tuh_itf_info_t", "structtuh__itf__info__t.html", null ],
    [ "tuh_xfer_s", "structtuh__xfer__s.html", null ],
    [ "tusb_desc_cs_video_fmt_t", "uniontusb__desc__cs__video__fmt__t.html", null ],
    [ "tusb_desc_cs_video_frm_t", "uniontusb__desc__cs__video__frm__t.html", null ],
    [ "tusb_desc_vc_itf_t", "structtusb__desc__vc__itf__t.html", null ],
    [ "tusb_desc_video_itf_hdr_t", "uniontusb__desc__video__itf__hdr__t.html", null ],
    [ "tusb_desc_vs_itf_t", "structtusb__desc__vs__itf__t.html", null ],
    [ "tusb_rhport_init_t", "structtusb__rhport__init__t.html", null ],
    [ "UARTDevice", "class_u_a_r_t_device.html", [
      [ "MotorSimplemotion", "class_motor_simplemotion.html", null ],
      [ "UART_CommandInterface", "class_u_a_r_t___command_interface.html", null ]
    ] ],
    [ "UartHandler", "class_uart_handler.html", [
      [ "UARTPort", "class_u_a_r_t_port.html", null ]
    ] ],
    [ "usb_log", "structusb__log.html", null ],
    [ "usb_string_desc", "structusb__string__desc.html", null ],
    [ "usb_xfer", "structusb__xfer.html", null ],
    [ "usbd_class_driver_t", "structusbd__class__driver__t.html", null ],
    [ "usbd_control_xfer_t", "structusbd__control__xfer__t.html", null ],
    [ "usbd_device_t", "structusbd__device__t.html", null ],
    [ "usbdcd_driver_s", "structusbdcd__driver__s.html", null ],
    [ "usbh_class_driver_t", "structusbh__class__driver__t.html", null ],
    [ "usbh_dev0_t", "structusbh__dev0__t.html", null ],
    [ "usbh_device_t", "structusbh__device__t.html", null ],
    [ "UsbHidHandler", "class_usb_hid_handler.html", [
      [ "FFBHIDMain", "class_f_f_b_h_i_d_main.html", null ],
      [ "HidFFB", "class_hid_f_f_b.html", null ]
    ] ],
    [ "USBOTG_FS_TypeDef", "struct_u_s_b_o_t_g___f_s___type_def.html", null ],
    [ "usbtmc_interface_state_t", "structusbtmc__interface__state__t.html", null ],
    [ "vendord_interface_t", "structvendord__interface__t.html", null ],
    [ "VescFlashAddrs", "struct_vesc_flash_addrs.html", null ],
    [ "cpp_freertos::WorkItem", "classcpp__freertos_1_1_work_item.html", null ],
    [ "cpp_freertos::WorkQueue", "classcpp__freertos_1_1_work_queue.html", null ],
    [ "xfer_ctl_t", "structxfer__ctl__t.html", null ],
    [ "xfer_desc_t", "structxfer__desc__t.html", null ],
    [ "xfer_dma_t", "structxfer__dma__t.html", null ],
    [ "xfer_td_t", "structxfer__td__t.html", null ]
];