var modules =
[
    [ "Audio", "group___class_driver___audio.html", "group___class_driver___audio" ],
    [ "Serial", "group___a_u_d_i_o___serial.html", "group___a_u_d_i_o___serial" ],
    [ "Communication Device Class (CDC)", "group___class_driver___c_d_c.html", "group___class_driver___c_d_c" ],
    [ "Human Interface Device (HID)", "group___class_driver___h_i_d.html", "group___class_driver___h_i_d" ],
    [ "MassStorage (MSC)", "group___class_driver___m_s_c.html", "group___class_driver___m_s_c" ],
    [ "Custom Class (not supported yet)", "group___group___custom.html", "group___group___custom" ],
    [ "common.h", "group___group___common_h.html", "group___group___common_h" ],
    [ "Compiler", "group___group___compiler.html", null ],
    [ "Error Codes", "group___group___error.html", "group___group___error" ],
    [ "fifo", "group__group__fifo.html", "group__group__fifo" ],
    [ "timeout timer", "group___group___timeout_timer.html", "group___group___timeout_timer" ],
    [ "USB Types", "group___u_s_b_def___type.html", "group___u_s_b_def___type" ],
    [ "Device Controller Driver (DCD)", "group__group__dcd.html", "group__group__dcd" ],
    [ "Host Controller Driver (HCD)", "group___group___h_c_d.html", "group___group___h_c_d" ],
    [ "Hub (Host only)", "group___class_driver___hub.html", "group___class_driver___hub" ],
    [ "Supported MCU", "group__group__mcu.html", null ],
    [ "Supported RTOS", "group__group__supported__os.html", null ],
    [ "EEPROM_Emulation", "group___e_e_p_r_o_m___emulation.html", "group___e_e_p_r_o_m___emulation" ],
    [ "Gamepad", "group___class_driver___h_i_d___gamepad.html", "group___class_driver___h_i_d___gamepad" ],
    [ "Mouse", "group___class_driver___h_i_d___mouse.html", "group___class_driver___h_i_d___mouse" ],
    [ "Keyboard", "group___class_driver___h_i_d___keyboard.html", "group___class_driver___h_i_d___keyboard" ],
    [ "Generic (not supported yet)", "group___class_driver___h_i_d___generic.html", "group___class_driver___h_i_d___generic" ],
    [ "Group_configuration", "group__group__configuration.html", null ]
];