name: Doxygen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Preparing
        run: mkdir ./docs
        
      - name: Doxygenize
        # You may pin to the exact commit or the version.
        # uses: langroodi/doxygenize@7410df330cf5ede72291d768e2e051c44181c491
        uses: langroodi/doxygenize@v1.6
        with:
          # Doxygen configuration file path
          doxygenconf: ./doc/Doxyfile # default is ./Doxyfile
          # Generated HTML documents output folder
          htmloutput: ./docs/ # default is ./docs/
          # GitHub Pages branch name
          ghpagesbranch: gh-pages # default is gh-pages
          # GitHub Pages directory path
          ghpagesdir: ./doxygen # default is ./
          # Toggle dark mode CSS
          #darkmode: # optional
